test: Just await an awaitable instead of wrapping it into get_success() twice
Not completely certain why this was raising with a different connection pool, but it looked like:
```
Traceback (most recent call last):
  File "/home/jason/dev/famedly/synapse-upstreaming/tests/unittest.py", line 128, in new
    return code(orig, *args, **kwargs)
  File "/home/jason/dev/famedly/synapse-upstreaming/tests/unittest.py", line 222, in setUp
    return orig()
  File "/home/jason/dev/famedly/synapse-upstreaming/tests/storage/test_appservice.py", line 144, in setUp
    super().setUp()
  File "/home/jason/dev/famedly/synapse-upstreaming/tests/unittest.py", line 397, in setUp
    self.hs = self.make_homeserver(self.reactor, self.clock)
  File "/home/jason/dev/famedly/synapse-upstreaming/tests/unittest.py", line 514, in make_homeserver
    hs = self.setup_test_homeserver(reactor=reactor, clock=clock)
  File "/home/jason/dev/famedly/synapse-upstreaming/tests/unittest.py", line 694, in setup_test_homeserver
    self.get_success(run_bg_updates())
  File "/home/jason/dev/famedly/synapse-upstreaming/tests/unittest.py", line 707, in get_success
    return self.successResultOf(deferred)
  File "/home/jason/.cache/pypoetry/virtualenvs/matrix-synapse-vUbQZmJ1-py3.13/lib/python3.13/site-packages/twisted/trial/_synctest.py", line 732, in successResultOf
    self.fail(
twisted.trial.unittest.FailTest: Success result expected on <Deferred at 0x7c565b339a20 current result: None>, found failure result instead:
Traceback (most recent call last):
  File "/home/jason/.cache/pypoetry/virtualenvs/matrix-synapse-vUbQZmJ1-py3.13/lib/python3.13/site-packages/twisted/internet/defer.py", line 1857, in _inlineCallbacks
    result = context.run(gen.send, result)
  File "/home/jason/dev/famedly/synapse-upstreaming/tests/unittest.py", line 680, in run_bg_updates
    self.get_success(stor.db_pool.updates.run_background_updates(False))
  File "/home/jason/dev/famedly/synapse-upstreaming/tests/unittest.py", line 706, in get_success
    self.pump(by=by)
  File "/home/jason/dev/famedly/synapse-upstreaming/tests/unittest.py", line 702, in pump
    self.reactor.pump([by] * 100)
  File "/home/jason/.cache/pypoetry/virtualenvs/matrix-synapse-vUbQZmJ1-py3.13/lib/python3.13/site-packages/twisted/internet/task.py", line 838, in pump
    self.advance(amount)
  File "/home/jason/dev/famedly/synapse-upstreaming/tests/server.py", line 651, in advance
    super().advance(amount)
  File "/home/jason/.cache/pypoetry/virtualenvs/matrix-synapse-vUbQZmJ1-py3.13/lib/python3.13/site-packages/twisted/internet/task.py", line 830, in advance
    call.func(*call.args, **call.kw)
  File "/home/jason/dev/famedly/synapse-upstreaming/synapse/util/clock.py", line 312, in wrapped_callback
    assert context.current_context() is context.SENTINEL_CONTEXT, (
builtins.AssertionError: Expected `call_later` callback from the reactor to start with the sentinel logcontext but saw run_bg_updates. In other words, another task shouldn't have leaked their logcontext to us.

```